### ISSUE TITLE
Unable to `pip install` packages.

### ISSUE THREAD

**Issue by AlvaroPata** [lewagon/data-setup#134]
I seem to be unable to use pip to install certain packages like `numpy`, `pandas` or `dotenv` on a given `pyenv` environment on a M1-MacBook Air.

I've tried updating `xcode-select`, `setuptools` and `wheel` but non yielded any results.

```shell
➜ pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/alephpei/.pyenv/versions/3.8.12/envs/comtools/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-install-sr4mje_9/dotenv_747d32c001b5422f8fb2b775e72f4686/setup.py'"'"'; __file__='"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-install-sr4mje_9/dotenv_747d32c001b5422f8fb2b775e72f4686/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-pip-egg-info-p9qxvhmc
         cwd: /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-install-sr4mje_9/dotenv_747d32c001b5422f8fb2b775e72f4686/
    Complete output (1589 lines):
        ERROR: Command errored out with exit status 1:
         command: /Users/alephpei/.pyenv/versions/3.8.12/envs/comtools/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setup.py'"'"'; __file__='"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-pip-egg-info-yi7x1rto
             cwd: /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/
        Complete output (15 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setuptools/__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setuptools/extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setuptools/dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setuptools/command/__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/setuptools/command/install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_e2997156b23e4dad80657a4786abad0a/pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        ----------------------------------------
    WARNING: Discarding https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip#sha256=3dc7a8d059dcf72f0ead2fa2144a24ee0ef07dce816e8c3545d7345767138c5e (from https://pypi.org/simple/distribute/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
        ERROR: Command errored out with exit status 1:
         command: /Users/alephpei/.pyenv/versions/3.8.12/envs/comtools/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/setup.py'"'"'; __file__='"'"'/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-pip-egg-info-0c7g8a40
             cwd: /private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/
        Complete output (10 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/setuptools/__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/setuptools/extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "/private/var/folders/37/hrj2n25s0szb0w7_wg4v0yw80000gn/T/pip-wheel-7aglt0px/distribute_b3164b4c41d24a6da43d4e7a4c1b03a3/setuptools/dist.py", line 103
            except ValueError, e:
                             ^
        SyntaxError: invalid syntax
        ----------------------------------------
```
Which repeats itself until it says:
```shell
WARNING: Discarding https://files.pythonhosted.org/packages/fa/5a/6dcdddeaa0ddc0bd331fdd1bc8696d9650ede0cb014083716976174eb4b8/dotenv-0.0.1.tar.gz#sha256=04006132a48e301a40b5bc3e8ea0d667a68981f277bb1785af0f8b9f7958e278 (from https://pypi.org/simple/dotenv/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dotenv (from versions: 0.0.1, 0.0.2, 0.0.4, 0.0.5)
ERROR: No matching distribution found for dotenv
```

**Comment by AlvaroPata** [comment]
There were some inconsistencies in my requirements.txt file! 

sorry!
